### PR TITLE
Avoid showing Ollama install screen when not required

### LINKED ISSUE #15: The extension quickly cycles through 4 or 5 screens before showing the actual UI
This is especially annoying in dark mode, where the screen flashes white in between:

CleanShot 2024-10-04 at 14 23 17

I would prefer to no hook up the output to the actual display for the first second, so all that visual noise only happens off-screen.

### PR DESCRIPTION
**Pull request by gunamata**
Fixes #15 

The PR eliminates showing the Ollama install screen when not required. The extension loading is still not as smooth as one would like to have but at least one less screen than earlier.

### CODE REVIEW

**Comment by jandubois** [comment]
> Fixes #15
>
> The PR eliminates showing the Ollama install screen when not required. The extension loading is still not as smooth as one would like to have but at least one less screen than earlier.

This PR may be removing the very first "installing" screen, but that makes almost no visible difference to me. So I wouldn't say it fixes #15.

We can merge this, if you want, but I would hope that the final fix that hides all the flashing pages would cover this initial screen as well, so maybe this PR would become redundant?

**Comment by gunamata** [comment]
Pushed an another commit that hides the iframe for a set interval (1 sec for now) at the time of loading.
With this change, we don't see the open webui splash screen any more.

**Comment by jandubois** [comment]
This is much better, but there is still a short flash of a black page before the page with the spinner is displayed:

CleanShot 2024-10-18 at 12 14 00

I'm scrubbing slowly through the recording to show it more clearly:

CleanShot 2024-10-18 at 12 16 13

Is there a way to get rid of that black page as well?

**Comment by gunamata** [comment]
I _think_ the black page is part of the extension loading in Rancher Desktop and not Open WebUI extension specific. So, It's better we file a separate issue to investigate the behavior related to the extension mechanism in Rancher Desktop.
 
Also, In my testing on Windows, I see the black screen only when switching to the extension view from a non extension page (Ex: Image, Troubleshooting etc). I don't see the black screen when switching between two extensions. Is this behavior the same on your machine (I assume macOS) too?

**Comment by jandubois** [comment]
> I _think_ the black page is part of the extension loading in Rancher Desktop and not Open WebUI extension specific.

I don't think so, I don't get it for other extensions:

CleanShot 2024-10-18 at 14 01 36

> I don't see the black screen when switching between two extensions.

Same for me, only when switching from a regular page to the Open WebUI page.

**Review by jandubois — APPROVED** [review]
Thanks, LGTM

**Pull request merged**
